

CREATE DATABASE 3103002090_Lokaverkefni;

CREATE TABLE Flokkur (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	nafn VARCHAR(20)
);

CREATE TABLE Tegund (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	nafn VARCHAR(20)
);

CREATE TABLE Utgefandi (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	nafn VARCHAR(50)
);

CREATE TABLE Flytjandi (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	nafn VARCHAR(50),
	Faedingardagur DATE NOT NULL,
	Danardagur DATE,
	Aldur INTEGER NOT NULL,
	Fjoldi_gefna_diska INTEGER NOT NULL,
	Flokkur_ID 
	
	
);